In [1]:
import pandas as pd

df = pd.read_csv('../../data/processed/final_dataset_clean.csv')

In [2]:
df.head()

,cluster_id,household_id,child_age_months,child_sex,breastfeeding,haz_score,waz_score,whz_score,stunted,underweight,...,district,wealth_index,disability,province,birth_weight_known,housing_quality,water_source,sanitation_type,education_level,household_education
0,1.0,1.0,59.0,0,2.0,-4.90,-1.64,1.72,1,0,...,1.0,2.0,1.0,0,0,2.0,31.0,1.0,0.0,0.0
1,1.0,1.0,46.0,1,2.0,-4.85,-2.04,0.95,1,0,...,1.0,2.0,2.0,0,0,2.0,31.0,1.0,0.0,0.0
2,1.0,4.0,48.0,0,2.0,-3.95,-0.79,1.95,1,0,...,1.0,1.0,2.0,0,0,2.0,22.0,1.0,0.0,0.0
3,1.0,4.0,35.0,0,2.0,-3.37,-4.00,-3.04,1,1,...,1.0,1.0,2.0,0,0,2.0,22.0,1.0,0.0,0.0
4,1.0,4.0,2.0,0,2.0,-2.88,-0.47,2.56,1,0,...,1.0,1.0,0.0,0,1,2.0,22.0,1.0,0.0,0.0

In [3]:
df.describe()

,cluster_id,household_id,child_age_months,child_sex,breastfeeding,haz_score,waz_score,whz_score,stunted,underweight,...,district,wealth_index,disability,province,birth_weight_known,housing_quality,water_source,sanitation_type,education_level,household_education
count,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,...,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000,61050.000000
mean,576.232629,10.433694,31.052449,0.484439,1.982031,-1.663041,-1.490027,-0.588196,0.450827,0.294627,...,16.231450,2.609517,1.267158,0.900966,0.683767,2.974693,29.016446,1.338346,0.833055,0.849304
std,331.778495,5.761642,16.969852,0.499762,0.663025,1.834946,1.297743,1.370528,0.497580,0.455879,...,9.121961,1.380146,0.931772,0.790192,0.465009,3.949376,19.606788,1.052685,1.422324,1.430907
min,1.000000,1.000000,0.000000,0.000000,1.000000,-6.000000,-6.000000,-5.990000,0.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,11.000000,1.000000,0.000000,0.000000
25%,284.000000,5.000000,16.000000,0.000000,2.000000,-2.850000,-2.290000,-1.360000,0.000000,0.000000,...,8.000000,1.000000,0.000000,0.000000,0.000000,2.000000,14.000000,1.000000,0.000000,0.000000
50%,592.000000,10.000000,32.000000,0.000000,2.000000,-1.640000,-1.540000,-0.630000,0.000000,0.000000,...,17.000000,2.000000,2.000000,1.000000,1.000000,2.000000,21.000000,1.000000,0.000000,0.000000
75%,873.000000,15.000000,46.000000,1.000000,2.000000,-0.490000,-0.690000,0.140000,1.000000,1.000000,...,25.000000,4.000000,2.000000,2.000000,1.000000,3.000000,32.000000,1.000000,1.000000,1.000000
max,1187.000000,20.000000,60.000000,1.000000,9.000000,6.000000,5.980000,6.000000,1.000000,1.000000,...,32.000000,5.000000,2.000000,2.000000,1.000000,99.000000,99.000000,9.000000,9.000000,9.000000

In [4]:
df.columns

Index(['cluster_id', 'household_id', 'child_age_months', 'child_sex',
       'breastfeeding', 'haz_score', 'waz_score', 'whz_score', 'stunted',
       'underweight', 'wasted', 'mother_education', 'urban_rural', 'district',
       'wealth_index', 'disability', 'province', 'birth_weight_known',
       'housing_quality', 'water_source', 'sanitation_type', 'education_level',
       'household_education'],
      dtype='str')

In [6]:
df.dtypes

cluster_id             float64
household_id           float64
child_age_months       float64
child_sex                int64
breastfeeding          float64
haz_score              float64
waz_score              float64
whz_score              float64
stunted                  int64
underweight              int64
wasted                   int64
mother_education       float64
urban_rural              int64
district               float64
wealth_index           float64
disability             float64
province                 int64
birth_weight_known       int64
housing_quality        float64
water_source           float64
sanitation_type        float64
education_level        float64
household_education    float64
dtype: object